ptx2/urls.py
from django.conf.urls import patterns, include, url
from ptx2app import views
from django.views.generic import RedirectView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # admin stuff
    url(r'^admin/scrape/$', 'ptx2app.views.scrape', name = 'scrape'),
    url(r'^admin/', include(admin.site.urls)),

    # core pages
    url(r'^$', RedirectView.as_view(url='/bookshelf/')), # redirect all rogue urls to bookshelf
	url(r'^bookshelf/', 'ptx2app.views.index'),
	url(r'^profile/', 'ptx2app.views.profile'),
    url(r'^history/', 'ptx2app.views.history'),
    url(r'^pending/$', 'ptx2app.views.pending'),
	url(r'^sellbook/', 'ptx2app.views.sell_book',  name = 'sell_book'),
	url(r'^(?P<isbn>\d+)/$', 'ptx2app.views.bookpage'),
	url(r'^courses/(?P<course_dpt>\w+)/(?P<course_num>\w+)/', 'ptx2app.views.coursepage'),
    url(r'^confirm/$', 'ptx2app.views.confirmbuybook'),
    url(r'^help/$', 'ptx2app.views.help'),
    url(r'^search/', 'ptx2app.views.search'),
    url(r'^searchcourses/', 'ptx2app.views.searchcourses'),
    url(r'^remove/', 'ptx2app.views.removecourse'),
    url(r'^markasowned/', 'ptx2app.views.markasowned'),
    url(r'^addtoneeded/', 'ptx2app.views.addtoneeded'),
    url(r'^removefromneeded/', 'ptx2app.views.removefromneeded'),
    url(r'^removefromselling/', 'ptx2app.views.removefromselling'),
    url(r'^removefromowned/', 'ptx2app.views.removefromowned'),
    url(r'^addcourse/', 'ptx2app.views.addcourse'),
    url(r'^remove_listing/$', 'ptx2app.views.remove_listing'),
    url(r'^buybook/$', 'ptx2app.views.buybook'),

    #CAS
    url(r'^login/$', 'django_cas.views.login'),
    url(r'^logout/$', 'django_cas.views.logout'),
    url(r'^accounts/login', 'django_cas.views.login'),
    url(r'^accounts/logout', 'django_cas.views.logout'),
)

ptx2app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


#abstract class of a book- not a physical book, but used to create book pages
class Book(models.Model):
    isbn = models.CharField(max_length=13)
    isbn10 = models.CharField(max_length=10)
    title = models.CharField(max_length=200)
    edition = models.CharField(max_length = 20, blank = True, null = True)
    authors = models.CharField(max_length = 500, blank = True, null = True)
    amazon_price = models.DecimalField(max_digits = 100, decimal_places = 2, blank = True, null = True)
    labyrinth_price = models.DecimalField(max_digits = 100, decimal_places = 2, blank = True, null = True)
    lowest_student_price = models.IntegerField(blank = True, null = True)
    picture_link = models.CharField(max_length = 1000, blank = True, null = True)
    def __unicode__(self):
        return self.title + ' (ISBN13: ' + self.isbn +')'

    def __getitem__(self, key):
        return getattr(self, key)
        
#course
class Course(models.Model):
    name = models.CharField(max_length = 500)
    dept = models.CharField(max_length = 3)
    num = models.CharField(max_length = 5) # Can't be IntegerField because of classes like 'ANT 206A'
    year = models.IntegerField()
    TERMS = (
            ('F', 'Fall'),
            ('S', 'Spring')
    )
    term = models.CharField(max_length = 1, choices = TERMS)
    books = models.ManyToManyField(Book, blank=True)
    # readings = models.ManyToManyField('Reading', blank=true) # use name since class Reading isn't defined yet
    def __unicode__(self):
        return self.name + ' (' + self.dept + ' ' + str(self.num) + ') ' + ' (' + self.term + ' ' + str(self.year) + ')'

    def __getitem__(self, key):
        return getattr(self, key)

#a physical book that you can own or sell
class PhysBook(models.Model):
    book = models.ForeignKey(Book)
    owner = models.ForeignKey("Profile")
    #comment = models.CharField(max_length = 500, blank=True)
    def __unicode__(self):
        return self.book.title + " owned by " + str(self.owner.pk)

# a review
class Review(models.Model):
    comment = models.CharField(max_length = 500, blank = True)
    def __unicode__(self):
        return self.comment

#a user's profile with extended information
class Profile(models.Model):
    user = models.ForeignKey(User)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    preferred_meetingplace = models.CharField(max_length=500, blank=True)
    reviews = models.ManyToManyField(Review, blank=True)
    #prof_pic = models.FileField()
    books_needed = models.ManyToManyField(Book, blank=True)
    books_owned = models.ManyToManyField(PhysBook, blank=True, related_name = 'books_owned')
    books_selling = models.ManyToManyField(PhysBook, blank=True, related_name = 'books_selling')
    course_list = models.ManyToManyField(Course, blank=True)
    def __unicode__(self):
        return self.user.username

#a listing that appears in each book page
class Listing(models.Model):
    book = models.ForeignKey(PhysBook)
    owner = models.ForeignKey(Profile)
    SELL_STATUSES = (
        ('O', 'Currently offered'),
        ('P', 'Sale pending'),
    )
    sell_status = models.CharField(max_length=1, choices=SELL_STATUSES, default='O')
    #price = models.DecimalField(max_digits = 100, decimal_places = 2)
    price = models.IntegerField()
    comment = models.CharField(max_length = 500, blank=True)
    def __unicode__(self):
        return self.book.book.title + " for $" + str(self.price)

# a transaction, current or pending
class Transaction(models.Model):
    buyer = models.ForeignKey(Profile, related_name = "transaction_buyer")
    seller = models.ForeignKey(Profile, related_name = "transaction_seller")
    book = models.ForeignKey(PhysBook)
    price = models.DecimalField(max_digits = 100, decimal_places = 2)
    buyerreview = models.ForeignKey(Review, blank=True, null=True, related_name = "buyerreview")
    sellerreview = models.ForeignKey(Review, blank=True, null=True, related_name = "sellerreview")
    
    def __unicode__(self):
        return self.seller.user.username + " sold to " + self.buyer.user.username + "for " + str(self.price)
  

ptx2app/forms.py
from django import forms
from ptx2app.models import *

class SellBookForm(forms.ModelForm):
    book = forms.ModelChoiceField(queryset = Book.objects.all())
    owner = forms.ModelChoiceField(queryset = Profile.objects.all())
    class Meta:
        model = Listing
        exclude = ['book', 'owner', 'sell_status']
        
class ProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		exclude = ['reviews', 'user']

class AddCourseForm(forms.Form):
    course = forms.CharField(max_length = 100)

class RemoveCourseForm(forms.Form):
    r = forms.CharField(max_length = 100)

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review

class PhysBookForm(forms.ModelForm):
	class Meta:
		model = PhysBook
		exclude = ['book']
		
class ListingForm(forms.ModelForm):
	class Meta:
		model = Listing
		fields= ['price']

ptx2app/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.contrib import messages
from ptx2app.models import *
from ptx2app.forms import *
from scraper import scrape as scrape_funcs
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.db.models import Q
from django.core.paginator import Paginator
from django.core.urlresolvers import resolve
import re
from operator import itemgetter
from django_cas.decorators import login_required
from helpers import set_lowest_price
from django.core.mail import send_mail, EmailMessage

# get the context of this request
def get_context(request):
    context = RequestContext(request)
    try:
        user = request.user
    except:
        HttpResponseRedirect("/login/")
    try:
        #profile = request.user.get_profile()
        profile = request.user.profile_set.get()
    except:
        profile = Profile.objects.create(user = user)
        profile.save()
    first = (not profile.first_name)
    books = Book.objects.all()
    transaction = Transaction.objects.all()

    nums_by_course = {}
    for course in profile.course_list.all():
        current_course = []
        for book in profile.books_owned.all():
            if book.book in course.books.all():
                if book.book not in current_course:
                    current_course.append(book.book)
        for book in profile.books_selling.all():
            if book.book in course.books.all():
                if book.book not in current_course:
                    current_course.append(book.book)
        nums_by_course[course] = len(current_course)

    num_total = len(profile.books_needed.all()) + len(profile.books_owned.all()) + len(Listing.objects.filter(owner = profile))

    context_dict = {'user' : profile,
                    'books' : books,
                    'num_needed' : len(profile.books_needed.all()),
                    'num_owned' : len(profile.books_owned.all()),
                    'num_selling' : len(Listing.objects.filter(owner = profile)),
                    'num_total' : num_total,
                    'num_pending' : len(Transaction.objects.filter(Q(buyer = profile)|Q(seller=profile), Q(buyerreview=None) | Q(sellerreview=None))),
                    'nums_by_course' : nums_by_course,
                    'user_selling': Listing.objects.filter(owner = profile),
                    'first_visit': first,
                    'user_transactions': Transaction.objects.filter(buyer = profile)
                    }
    return context_dict

#the main bookshelf page
@login_required
def index(request):

    context = RequestContext(request)
    
    if not request.user.is_authenticated():
        return redirect('/login/')
    context_dict = get_context(request)
    
    profile = context_dict['user']
    nums_by_course = {}
    for course in profile.course_list.all():
        num = 0
        for book in profile.books_owned.all():
            if course.books.all() == book:
                num += 1
        nums_by_course[course] = num

    #contextdict = get_context(request)


    return render_to_response('ptonptx2/bookshelf.html', context_dict, context)

@login_required
#loads the page for each book
def bookpage(request, isbn):
    context = RequestContext(request)
    if not request.user.is_authenticated():
        return redirect('/login/')
    
    context_dict = get_context(request)
    try:
        book = Book.objects.get(isbn=isbn)
    except:
        context_dict = get_context(request)
        return render_to_response('ptonptx2/book_lookup_error.html', context_dict, context)
    listings = Listing.objects.filter(book__book__isbn = isbn, sell_status = 'O')
    
    context_dict['listings'] = listings
    context_dict['book'] = book
    context_dict['courses'] = Course.objects.filter(books = book)
    
    return render_to_response('ptonptx2/book_lookup.html', context_dict, context)
    
@login_required
#loads the about page
def about(request):
    context = RequestContext(request)
    if not request.user.is_authenticated():
        return redirect('/login/')
    
    return render_to_response('ptonptx2/about.html', context)

@login_required
#handles the selling the book once user clicks on specific listing
def sell_book(request):
    context = RequestContext(request)
    if not request.user.is_authenticated():
        return redirect('/login/')
    if request.method == 'POST':

        if len(request.POST['price']) == 0:
            messages.error(request, 'No price given. Please try again.')
            return HttpResponseRedirect("/bookshelf/")
        try:
            price = int(float(request.POST['price']))
        except:
            messages.error(request, "Invalid price given. Please use only numbers.")
            return HttpResponseRedirect("/bookshelf/")
        if price < 1:
            messages.error(request, "Invalid price given. Price must be greater than $1.")
            return HttpResponseRedirect("/bookshelf/")

        # if this is an edit, the POST will contain a 'listingpk' field

        if 'listingpk' in request.POST:
            pk = request.POST['listingpk']
            listing = Listing.objects.get(pk = pk)
            if listing.sell_status == 'P':
                messages.error(request, "Someone has already made an offer on this book. You can't edit the listing.")
                return HttpResponseRedirect("/bookshelf")
            listing.price = price
            listing.comment = request.POST['comment']
            listing.save()
            
            #set lowest student price
            set_lowest_price(listing.book.book)

            return HttpResponseRedirect("/"+request.POST['next'])

        # if this field doesn't exist, it's a new listing
        listing = Listing()
        user = request.user.profile_set.get()
        book = Book.objects.get(pk = request.POST['bookpk'])

        #if there is already a physbook, use it. If not, check to see if the user has any of this book
        #marked as owned. If not, make a new physbook
        try:
            physbook = PhysBook.objects.get(pk = request.POST['pk'])
            user.books_owned.remove(physbook)
        except:
            try:
                physbook = user.books_owned.filter(book__pk = request.POST['bookpk'])[0]
                user.books_owned.remove(physbook)
            except IndexError:
                physbook = PhysBook()
                physbook.owner = user
                physbook.book = book
                physbook.save()

        #add book to user's list of books for sale
        user.books_selling.add(physbook)
        user.save()

        listing.book = physbook
        listing.owner = user
        listing.sell_status = 'O'
        listing.price = price
        listing.comment = request.POST['comment']
        listing.save()
        set_lowest_price(physbook.book)
        return HttpResponseRedirect('/bookshelf/')

    else:
        return HttpResponseRedirect("/bookshelf/")

    return render_to_response('forms/newlisting.html', context)

#remove the listing with the given id, return the book to the seller's owned books
@login_required
def remove_listing(request):
    context = RequestContext(request)
    if not request.POST:
        return HttpResponseRedirect("/bookshelf")
    listingid=request.POST['listingid']
    listing = Listing.objects.get(pk = listingid)
    owner = listing.owner
    # make sure the person can only remove their own listings
    if not owner == request.user.profile_set.get():
        messages.error(request, "You can't remove that listing. Are you trying to break the site?")
        return HttpResponseRedirect("/bookshelf")
    if listing.sell_status == 'P':
        messages.error(request, "Sorry, someone has already purchased this book. You may cancel the transaction if you'd like.")
        return HttpResponseRedirect("/bookshelf/")
    physbook = listing.book
    owner.books_selling.remove(physbook)
    owner.books_owned.add(physbook)
    owner.save()

    listprice = listing.price
    listing.delete()

    set_lowest_price(physbook.book)

    return HttpResponseRedirect("/" + physbook.book.isbn + "/")

@login_required
#allows user to edit their profile
def profile(request):
    context = RequestContext(request)
    if not request.user.is_authenticated():
        return redirect('/login/')
    if request.POST:
        if len(request.POST['first_name']) == 0 or len(request.POST['last_name']) == 0 or len(request.POST['pref_meeting_place']) == 0:
            messages.error(request, "Invalid form. No action taken.")
        else:
            profile = request.user.profile_set.get()
            profile.first_name = request.POST['first_name']
            profile.last_name = request.POST['last_name']
            profile.preferred_meetingplace = request.POST['pref_meeting_place']
            profile.save()
            messages.success(request, "Profile updated.")
    return HttpResponseRedirect("/bookshelf")

@login_required
#loads the user's history of transactions
def history(request):
    context = RequestContext(request)
    if not request.user.is_authenticated():
        return redirect('/login/')
    profile = request.user.get_profile()
    context_dict = get_context(request)
    transaction = Transaction.objects.all()
    past_transactions = []
    
    for instance in transaction:
    	#if the transaction has both reviews filled make it show up
        if (instance.buyerreview != None) & (instance.sellerreview != None):
            if profile == instance.buyer:
                past_transactions.append(instance)
            if profile == instance.seller:
                past_transactions.append(instance)
    past_transactions.sort(key=lambda tr: tr.pk)
    context_dict['history'] = past_transactions
    return render_to_response('ptonptx2/history.html', context_dict, context)

@login_required

ptx2app/templates/forms/addtoneeded.html
<div class="modal fade addtoneededmodal" tabindex="-1" role="dialog" aria-labelledby="addtoneededmodal" aria-hidden="true" id="addtoneededmodal{{book.id}}">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel">Add <i>{{book.title}}</i> to needed?</h5>
            </div>
            <div class="modal-body">
                <div align="right">
                    <form name="addtoneeded" method="post" action="/addtoneeded/">{%csrf_token%}
                        <input type="hidden" name="m" value="{{book.id}}"></input>
                        <input name="Add to needed" type="submit" class="btn btn-danger"></input>
                        <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>          
</div>

ptx2app/templates/forms/editlisting.html
<div class="modal fade editlistingmodal" tabindex="-1" role="dialog" aria-labelledby="editlistingmodal" aria-hidden="true" id="editlistingmodal{{listing.pk}}">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Edit listing of "{{ title }}"</h4>
                </div>
                <div class="modal-body">
                    <p>Just as a reminder, the prices this book is currently going for are:</p>
                    <p>
                    {% include 'forms/price_widget.html' with labprice=labprice amazprice=amazprice lowstud=lowstud isbn=isbn isbn10=isbn10 inc_PU=True%}
                    </p>
                    <form action="/sellbook/" method="POST" id="sellbookform">{% csrf_token %}
                        <div class="form-group">
                            <label for="id_price">Price:</label>
                            <div class="input-group">
                                <span class="input-group-addon">$</span>
                                <input id="id_price{{listingpk}}" name="price" value="{{curprice}}" step="1" min="1" type="number" class="form-control" required>
                                <span class="input-group-addon">.00</span>
                            </div>
                            <br>
                            <label for="id_comment">Comment:</label>
                            <input type="textarea" name="comment" value="{{curcomm}}" id="id_comment" maxlength="500" class="form-control" rows="3" />
                            <br>
                            <div align="right">
                                <input type="submit" name="Submit" class="btn btn-primary">
                                <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                            </div>
                        </div>
                        <input type="hidden" name="listingpk" value="{{listingpk}}">
                        <input type="hidden" name="next" value={{next}}>
                    </form>
                </div>
            </div>          
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#editlistingmodal{{listing.pk}}').on('shown.bs.modal', function() {$('#id_price{{listingpk}}').focus()});
</script>

ptx2app/templates/forms/firstvisitmodal.html
<div class="modal fade firstvisitmodal" tabindex="-1" role="dialog" aria-labelledby="firstvisitmodal" aria-hidden="true" id="firstvisitmodal" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="firstvisitmodal">Welcome to PTX2!</h4>
            </div>
            <div class="modal-body">
                <div>This appears to be your first visit to our site.<br><br>
                To get started, please fill out your name and preferred meeting place. These will be sent in emails to people you buy from and sell to in order to smooth out the transaction process.<br><br>
                    <form action="/profile/" method="POST" id="editprofile">{% csrf_token %}
                        <div class="form-group">
                            <label for="id_first_name_first">First name:</label>
                            <div class="input-group">
                                <input id="id_first_name_first" name="first_name" type="text" class="form-control" required>
                            </div>
                            <br>
                            <label for="id_last_name">Last name:</label>
                            <div class="input-group">
                                <input id="id_last_name_first" name="last_name" type="text" class="form-control" required>
                            </div>
                            <br>
                            <label for="id_pref_meeting_place">Preferred meeting place:</label>
                            <div class="input-group">
                                <input id="id_pref_meeting_plac_first" name="pref_meeting_place" type="text" class="form-control" required>
                            </div>
                            <div align="right">
                                <input type="submit" name="Submit" class="btn btn-primary">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>          
    </div>
</div>
<script type="text/javascript">
    $('#firstvisitmodal').on('shown.bs.modal', function() {$('#id_first_name_first').focus()});
</script>

ptx2app/templates/forms/markasowned.html
<div class="modal fade markasownedmodal" tabindex="-1" role="dialog" aria-labelledby="markasownedmodal" aria-hidden="true" id="markasownedmodal{{book.id}}">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel">Mark <i>{{book.title}}</i> as owned?</h5>
            </div>
            <div class="modal-body">
                <div align="right">
                    <form name="markasowned" method="post" action="/markasowned/"> {% csrf_token %}
                        <input type="hidden" name="m" value="{{book.id}}"></input>
                        <input name="Mark as owned" type="submit" class="btn btn-danger"></input>
                        <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>          
</div>

ptx2app/templates/forms/newcourse.html
<div class="modal fade newcoursemodal" tabindex="-1" role="dialog" aria-labelledby="newcoursemodal" aria-hidden="true" id="newcoursemodal">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title" id="myModalLabel">Add new course</h4>
				</div>
				<div class="modal-body">
					<form id="addnewcourseform" method="get" name="addnewcourseform" action="/searchcourses/">
					<div class="form-group">
                        <input type="text" class="form-control" data-provide="typeahead" placeholder="Search for courses to add (e.g. 'COS333' or 'COS')" name="q" id="newCourseInput"><br>
                        <div align="right">
                            <input type="submit" name="Search courses" class="btn btn-primary">
                            <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                        </div>
                    </div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$('#newcoursemodal').on('shown.bs.modal', function() {$('#newCourseInput').focus()});
</script>

ptx2app/templates/forms/newlisting.html
<div class="modal fade newlistingmodal" tabindex="-1" role="dialog" aria-labelledby="newlistingmodal" aria-hidden="true" id="newlistingmodal{{book.pk}}">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Selling "{{ title }}"</h4>
                </div>
                <div class="modal-body">
                    <p>Just as a reminder, the prices this book is currently going for are:</p>
                    <p>
                    {% include 'forms/price_widget.html' with labprice=labprice amazprice=amazprice lowstud=lowstud isbn=isbn isbn10=isbn10 inc_PU=True%}
                    </p>
                    <form action="/sellbook/" method="POST" id="sellbookform">{% csrf_token %}
                        <div class="form-group">
                            <label for="id_price">Price:</label><div class="input-group">
                                <span class="input-group-addon">$</span>
                                <input id="id_price{{book.pk}}" name="price" step="1" min="1" type="number" class="form-control" required>
                                <span class="input-group-addon">.00</span>
                            </div><br>
                            <label for="id_comment">Comment:</label><input type="textarea" name="comment" id="id_comment" maxlength="500" class="form-control" rows="3" /><br>
                            <div align="right">
                                <input type="submit" name="Submit" class="btn btn-primary">
                                <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                            </div>
                        </div>
                        <input type="hidden" name="pk" value="{{ pk }}">
                        <input type="hidden" name="bookpk" value="{{ bookpk }}">
                    </form>
                </div>
            </div>          
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#newlistingmodal{{book.pk}}').on('shown.bs.modal', function() {$('#id_price{{book.pk}}').focus()});
</script>

ptx2app/templates/forms/price_widget.html
<img src="http://www.labyrinthbooks.com/favicon.ico" height="16"; width="16">
{% if labprice|default:None %}
<a href="http://www.labyrinthbooks.com/all_detail.aspx?isbn={{isbn}}" target="_blank">
    ${{ labprice }}
</a>
{% else %}
None
{% endif %}
<br>
<img src="http://www.amazon.com/favicon.ico" height="16"; width="16">
{% if amazprice|default:None %}
<a href="http://www.amazon.com/gp/product/{{ isbn10 }}" target="_blank">
    ${{ amazprice }}
</a>
{% else %}
None
{% endif %}
<br>
{% if inc_PU|default:False %}
<img src="http://www.princeton.edu/favicon.ico" height="16"; width="16"> 
    {% if lowstud != None|default:None %}
    <a href="/{{ book.isbn }}">${{ lowstud }}.00</a><br>
    {% else %}
    No student offers<br>
    {% endif %}
{% endif %}

ptx2app/templates/forms/profilemodel.html
<div class="modal fade profilemodal" tabindex="-1" role="dialog" aria-labelledby="profilemodal" aria-hidden="true" id="profilemodal">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Change your profile details</h4>
            </div>
            <div class="modal-body">
                <div>
                    <form name="profilemodal" method="post" action="/profile/">{% csrf_token %}
                        <div class="form-group">
                            <label for="id_first_name">First name:</label>
                            <div class="input-group">
                                <input id="id_first_name" name="first_name" value="{{first_name}}" type="text" class="form-control" required>
                            </div>
                            <br>
                            <label for="id_last_name">Last name:</label>
                            <div class="input-group">
                                <input id="id_last_name" name="last_name" value="{{last_name}}" type="text" class="form-control" required>
                            </div>
                            <br>
                            <label for="id_pref_meeting_place">Preferred meeting place:</label>
                            <div class="input-group">
                                <input id="id_pref_meeting_plac" name="pref_meeting_place" value="{{pref_place}}" type="text" class="form-control" required>
                            </div>
                            <div align="right">
                                <input type="submit" name="Submit" class="btn btn-primary">
                                <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div> 
</div>
<script type="text/javascript">
    $('#profilemodal').on('shown.bs.modal', function() {$('#id_first_name').focus()});
</script>

ptx2app/templates/forms/removecourse.html
<div class="modal fade removecoursemodal" tabindex="-1" role="dialog" aria-labelledby="removecoursemodal" aria-hidden="true" id="removecoursemodal{{course.id}}">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel">Remove <i>{{course.name}}</i>?</h5>
            </div>
            <div class="modal-body">
                <div align="right">
                    <form name="removecourse" method="post" action="/remove/">{% csrf_token %}
                        <input type="hidden" name="r" value="{{course.id}}"></input>
                        <input name="Delete" type="submit" class="btn btn-danger" value="Remove"></input>
                        <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>          
</div>